import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

class PDFReportGenerator:
    def __init__(self, kg, model, explainer):
        self.kg = kg
        self.model = model
        self.explainer = explainer
        
    def generate_report(self, disease_id, output_path):
        disease_name = self.kg.graph.nodes[disease_id]["name"]
        
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54
        )
        
        styles = getSampleStyleSheet()
        
        primary_color = colors.HexColor("#0f172a") # Slate-900
        secondary_color = colors.HexColor("#06b6d4") # Cyan-500
        text_color = colors.HexColor("#334155") # Slate-700
        
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=primary_color,
            spaceAfter=10
        )
        
        subtitle_style = ParagraphStyle(
            "ReportSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=10,
            leading=12,
            textColor=colors.HexColor("#64748b"),
            spaceAfter=20
        )
        
        heading2_style = ParagraphStyle(
            "SectionHeader",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=secondary_color,
            spaceBefore=12,
            spaceAfter=8,
            keepWithNext=True
        )
        
        body_style = ParagraphStyle(
            "BodyText",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13.5,
            textColor=text_color,
            spaceAfter=6
        )
        
        table_header_style = ParagraphStyle(
            "TableHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            textColor=colors.white
        )
        
        table_cell_style = ParagraphStyle(
            "TableCell",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=10.5,
            textColor=text_color
        )
        
        story = []
        
        # --- TITLE ---
        story.append(Paragraph("AI-Guided Drug Repurposing Report", title_style))
        story.append(Paragraph(f"Target Indication: <b>{disease_name}</b>", ParagraphStyle("IndicationTitle", parent=body_style, fontSize=11, leading=15, textColor=primary_color)))
        story.append(Paragraph("Generated by Upgraded Nebula Platform Engine", subtitle_style))
        story.append(Spacer(1, 5))
        
        # --- EXECUTIVE SUMMARY ---
        story.append(Paragraph("1. Executive Summary", heading2_style))
        exec_summary_text = (
            f"This analysis report identifies promising candidate compounds for repurposing against "
            f"<b>{disease_name}</b>. The predictions are generated by an upgraded machine learning model "
            f"trained on multi-scale topological features extracted from a comprehensive biological knowledge graph. "
            f"To guarantee clinical and mechanistic interpretability, each recommendation includes a multi-factor "
            f"confidence breakdown, side-effect profiling, and PubMed literature evidence mapping."
        )
        story.append(Paragraph(exec_summary_text, body_style))
        
        # --- PREDICTIONS TABLE ---
        story.append(Paragraph("2. Top Repurposing Recommendations", heading2_style))
        
        predictions = self.model.predict_repurposing(disease_id)
        candidates = [p for p in predictions if not p["is_approved"]]
        
        table_data = [[
            Paragraph("Rank", table_header_style),
            Paragraph("Drug Name", table_header_style),
            Paragraph("Confidence Score", table_header_style),
            Paragraph("Network Sim.", table_header_style),
            Paragraph("Pathway Overlap", table_header_style),
            Paragraph("Lit. Evidence", table_header_style)
        ]]
        
        for idx, cand in enumerate(candidates[:6]):
            bd = cand["confidence_breakdown"]
            table_data.append([
                Paragraph(str(idx + 1), table_cell_style),
                Paragraph(cand["drug_name"], table_cell_style),
                Paragraph(f"<b>{cand['confidence_score']}%</b>", table_cell_style),
                Paragraph(f"{bd['network_similarity']}%", table_cell_style),
                Paragraph(f"{bd['pathway_overlap']}%", table_cell_style),
                Paragraph(f"{bd['literature_evidence']}%", table_cell_style)
            ])
            
        t = Table(table_data, colWidths=[40, 130, 90, 80, 80, 80])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")]),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('TOPPADDING', (0,0), (-1,-1), 5),
        ]))
        story.append(t)
        story.append(Spacer(1, 10))
        
        # --- DETAILED TOP CANDIDATE ---
        if candidates:
            top_cand = candidates[0]
            top_drug_id = top_cand["drug_id"]
            top_drug_name = top_cand["drug_name"]
            
            story.append(Paragraph(f"3. Upgraded Mechanistic Profiling: {top_drug_name}", heading2_style))
            
            # Drug details
            drug_info = self.kg.get_drug_info(top_drug_id)
            story.append(Paragraph(f"<b>Mechanism of Action:</b> {drug_info['moa']}", body_style))
            story.append(Paragraph(f"<b>Side-effect Profile:</b> {', '.join(drug_info['side_effects'])}", body_style))
            story.append(Spacer(1, 5))
            
            # Explanation agent output
            exp_data = self.explainer.explain_prediction(top_drug_id, disease_id)
            story.append(Paragraph(f"<b>Discovery Explanation:</b> {exp_data['text_summary']}", body_style))
            story.append(Spacer(1, 5))
            
            # Literature citations bibliography
            story.append(Paragraph("<b>4. PubMed Peer-reviewed Bibliography & Supporting Studies</b>", heading2_style))
            citations = self.kg.get_pubmed_citations(top_drug_id, disease_id)
            
            for cit in citations:
                cit_text = (
                    f"• <b>PMID: {cit['pmid']}</b> - {cit['title']} "
                    f"<i>{cit['journal']}</i> ({cit['year']}) - <b>[{cit['type']}]</b>"
                )
                story.append(Paragraph(cit_text, ParagraphStyle("CitStyle", parent=body_style, leftIndent=15, spaceAfter=4)))
                
        story.append(Spacer(1, 10))
        
        # --- METHODOLOGY ---
        story.append(Paragraph("5. Methodology Summary", heading2_style))
        methodology_text = (
            "The Upgraded Nebula Platform aggregates biological similarity, pathway overlap indices, target convergence ratios, "
            "and active clinical bibliographies into a segmented score. Predictions are run against a multi-modal "
            "knowledge graph incorporating MAO-B, DRD2, and protein-protein network structures. "
            "Local explainability is mapped using cooperative SHAP values based on game theory."
        )
        story.append(Paragraph(methodology_text, body_style))
        
        doc.build(story)
